controller_manager:
  ros__parameters:
    update_rate: 50. #NEED TO MATCH THIS TO IRL CONTROL LOOP RATE , 50 good for now
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.635 # MEASURE IN CLASS done
    wheel_radius: 0.161 # MEASURE IN CLASS done

    use_stamped_vel: false

    #HIGH FIDELITY LIMITS 
    mobile_base_config: 
      linear:
        x: 
          has_velocity_limits: true
          max_velocity: 2 #m/s , project cap
          has_acceleration_limits: true
          max_acceleration: 1 #m/s^2 , project cap
        angular: 
          z: 
            has_velocity_limits: true
            max_velocity: 6.299 #rad/s . w_max = 2*(2m/s)/.635 [axle length]
            has_acceleration_limits: true
            max_acceleration: 3.15 #rad/s^2 . a_max = 2*(1m/s^2)/.635 [axle length]
          
  

    # open_loop: false    

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN




# joint_broad:
#   ros__parameters: